name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Build
        run: pnpm run build
